image: registry.cmusatyalab.org/coda/coda-packaging/coda-build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - mkdir -p ccache
  - export CCACHE_BASEDIR="${PWD}"
  - export CCACHE_DIR="${PWD}/ccache"
  - export CCACHE_NOHASHDIR=true
  - export CC="/usr/bin/ccache gcc"
  - export CXX="/usr/bin/ccache g++"

cache:
  paths:
    - ccache/

test_build:
  stage: build
  script:
    - tools/version_check.sh
    - ./bootstrap.sh
    - ./configure --prefix=/usr --with-lua
    - make all
  except:
    - tags
    - rc

build_source:
  stage: build
  script:
    - tools/version_check.sh
    - ./bootstrap.sh --fix-versions
    - ./configure --prefix=/usr --with-lua
    - make distcheck dist-xz
  artifacts:
    expire_in: 1 week
    paths:
      - "coda-*.tar*"
  only:
    - tags
    - rc

test_doc:
  stage: build
  script:
    - doxygen doxygen/Doxyfile
  except:
    - master

pages:
  stage: build
  script:
    - doxygen doxygen/Doxyfile
    - mv doxygen/html/ public/
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
